name: YASL CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yasl-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run unit tests
        run: |
          uv run pytest --cov=src/yasl --cov-report=xml --cov-fail-under=75 tests/yasl

      - name: Check formatting with ruff
        run: |
          uv run ruff check src/yasl tests/yasl

      - name: Run BDD tests with Behave
        run: |
          uv run behave ./features

      - name: Check CLI tool
        run: |
          uv run yasl --version
          uv run yasl --help

  yaql-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]
        
  yarl-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]

  check-build:
    needs: [yasl-ci, yaql-ci, yarl-ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your desired Python version

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]
        
      - name: Build package
        run: |
          uv run python -m build